---

- name: Install Composer
  shell: "curl -sS https://getcomposer.org/installer | {{ php_install_path }}/bin/php -- --install-dir={{ php_composer_install_path }} --filename=composer installer warn=no"
  args:
    creates: /usr/local/bin/composer
  tags: [php, composer]

