---

- name: Make sure that epel repository is present
  yum:
    name: epel-release
    state: latest
  tags: [php, install]

- name: Install required tools for compiling PHP
  yum:
    name: ['autoconf', 'libtool', 're2c', 'bison', 'libxml2-devel', 'bzip2-devel', 'libcurl-devel', 'libpng-devel', 'libicu-devel', 'gcc-c++', 'libmcrypt-devel', 'libwebp-devel', 'libjpeg-devel', 'openssl-devel']
    state: latest
  tags: [php, install]


# https://github.com/php/php-src/releases
#
- name: Download PHP source files
  get_url:
    dest: "{{ php_sources_location }}"
    url: "https://github.com/php/php-src/archive/php-{{ php_version }}.tar.gz"
  tags: [php, install]

- name: Unpack downloaded PHP sources
  unarchive:
    src: "{{ php_sources_location }}/php-src-php-{{ php_version }}.tar.gz"
    dest: "{{ php_sources_location }}"
    owner: "{{ build_user }}"
    group: "{{ build_group }}"
    copy: no
    creates: "{{ php_sources_location }}/php-src-php-{{ php_version }}"
  tags: [php, install]


#Add bison 2.7 to PATH if php 5.6
- set_fact:
    php_bison_path: "{{ php_bison_install_path }}/bin:{{ ansible_env.PATH }}"
  when: php_bison_installtion == true
  tags: [php, install]

- set_fact:
    php_bison_path: "{{ ansible_env.PATH }}"
  when: php_bison_installtion == false
  tags: [php, install]  

- name: Compile PHP
  command: "{{ item }}"
  args:
    chdir: "{{ php_sources_location }}/php-src-php-{{ php_version }}"
  with_items:
    - ./buildconf --force
    - "./configure {{ php_configure_options | join(' ') }}"
    - make clean
    - make
  become: true
  become_user: "{{ build_user }}"
  environment:
    PATH: "{{ php_bison_path }}"
  tags: [php, install]

- name: Install compiled PHP
  command: make install
  args:
    chdir: "{{ php_sources_location }}/php-src-php-{{ php_version }}"
  tags: [php, install]

- name: Copy php.ini file to installation path
  copy:
    src: "{{ php_sources_location }}/php-src-php-{{ php_version }}/php.ini-production"
    dest: "{{ php_ini_file_path }}"
    remote_src: yes
    force: no
    owner: root
    group: root
    mode: 0644
  tags: [php, install]

- name: Cleanup downloaded sources
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ php_sources_location }}/php-src-php-{{ php_version }}.tar.gz"
    - "{{ php_sources_location }}/php-src-php-{{ php_version }}"
  when: "php_cleanup_after_install == true"
  tags: [php, install, cleanup]

- name: Add PHP executables to PATH
  template:
    src: php.sh.j2
    dest: /etc/profile.d/php.sh
    owner: root
    group: root
    mode: 0644
  when: "php_set_executable_path == true"
  tags: [php, install]

- name: Add Systemd entry for PHP-FPM
  template:
    src: php-fpm.service.j2
    dest: "/etc/systemd/system/{{ php_codename }}-fpm.service"
    owner: root
    group: root
    mode: 0644
  tags: [php, install]
