---

- name: Enable OPcache extension
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "zend_extension = opcache.so"
    state: present
    insertafter: "[PHP]"
  notify: restart php-fpm
  when: "php_opcache_enable == '1'"
  tags: [php, opcache]

- name: Disable OPcache extension
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "zend_extension = opcache.so"
    state: absent
    insertafter: "[PHP]"
  notify: restart php-fpm
  when: "php_opcache_enable == '0'"
  tags: [php, opcache]

- name: Enable OPcache
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.enable = {{ php_opcache_enable }}"
    state: present
    regexp: '^;?opcache\.enable'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]

- name: Set memory consumption
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.memory_consumption = {{ php_opcache_memory_consumption }}"
    state: present
    regexp: '^;?opcache\.memory_consumption'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]

- name: Set interned strings buffer
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.interned_strings_buffer = {{ php_opcache_interned_strings_buffer }}"
    state: present
    regexp: '^;?opcache\.interned_strings_buffer'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]

- name: Set maximum number of accelerated files
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.max_accelerated_files = {{ php_opcache_accelerated_files }}"
    state: present
    regexp: '^;?opcache\.max_accelerated_files'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]

- name: Set timestamp validation
  lineinfile:
    dest: "{{ php_ini_file_path }}"
    line: "opcache.validate_timestamps = {{ php_opcache_validated_timestamps }}"
    state: present
    regexp: '^;?opcache\.validate_timestamps'
    insertafter: "[opcache]"
  notify: restart php-fpm
  tags: [php, opcache]
